apiVersion: v1
kind: Service
metadata:
  name: rakheoananpservice-srv
spec:
  type: NodePort
  selector:
    app: rakheoana
  ports:
  - name: rakheoana
    protocol: TCP
    port: 80
    targetPort: 80
