apiVersion: apps/v1
kind: Deployment
metadata:
  name: rakheoana-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rakheoana
  template:
    metadata:
      labels:
        app: rakheoana
    spec:
      containers:
      - name: rakheoana
        image: rakgew/rakheoana:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
